


# Tell Quarkus to use Ollama as the primary AI provider
quarkus.langchain4j.provider=ollama

# Point to your local Ollama instance
quarkus.langchain4j.ollama.base-url=http://localhost:11434

# Select your local model
quarkus.langchain4j.ollama.chat-model.model-name=qwen3.5:0.8b
quarkus.langchain4j.ollama.chat-model.temperature=0.3

# Crucial for local LLMs running on developer hardware
quarkus.langchain4j.timeout=90s


%test.client.quarkus.oidc.auth-server-url=http://localhost:42381/realms/quarkus
%test.keycloak.auth-server-internal-url=http://localhost:42381/realms/quarkus
%test.keycloak.realms=quarkus
%test.keycloak.url=http://localhost:42381
%test.oidc.users=alice=alice,bob=bob
%test.quarkus.oidc.auth-server-url=http://localhost:42381/realms/quarkus
%test.quarkus.oidc.client-id=quarkus-app
%test.quarkus.oidc.credentials.secret=secret