


# Tell Quarkus to use openai as the primary AI provider



quarkus.langchain4j.timeout=180s
quarkus.langchain4j.devservices.enabled=false
quarkus.langchain4j.openai.devservices.enabled=false
quarkus.langchain4j.openai.base-url=http://192.168.1.9:8080/v1
quarkus.langchain4j.openai.chat-model.model-id=Qwen/Qwen2.5-Coder-3B-Instruct-GGUF
quarkus.langchain4j.openai.chat-model.temperature=0.3
quarkus.langchain4j.openai.chat-model.format="json"

# Logging
quarkus.langchain4j.openai.log-requests-curl=true
quarkus.langchain4j.openai.log-requests=true
quarkus.langchain4j.openai.log-responses=true


# Point to your local openai instance
#quarkus.langchain4j.openai.base-url=http://localhost:11434

# Select your local model

# Crucial for local LLMs running on developer hardware




quarkus.oidc.auth-server-url=https://login.antoniocaccamo.work/realms/labs
quarkus.oidc.client-id=recipe-builder
quarkus.oidc.credentials.secret=fqtOwZusbXvWNjJrdAjSK9iDEy2f4KDE
quarkus.oidc.key.application-type=service

quarkus.langchain4j.openai.embedding-model.enabled=true

quarkus.langchain4j.openai.*.embedding-model.log-requests=true

quarkus.langchain4j.openai.*.embedding-model.log-responses=true
